services:
  ticket-manager-service:
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: ticket-manager
    depends_on:
      db-ticket-manager:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s


  db-ticket-manager:
    image: postgres
    container_name: db-ticket-manager
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: TicketManagerDatabase
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket_user -d TicketManagerDatabase"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 10s
    volumes:
      - db_ticket_manager_data:/var/lib/postgresql/data

volumes:
  db_ticket_manager_data: